import { columns, Payment } from "@/components/columns"
import { DataTable } from "@/components/data-table";

async function getData(): Promise<Payment[]> {
  // Fetch data from your API here.
  return  [
    {
      uid: "stu1",
      name: "Olivia Chen",
      email: "olivia.chen@example.com",
      rollNumber: "2023001",
      branch: "CSE",
      year: "Third",
      semester: "5",
      gender: "Female",
    },
    {
      uid: "stu2",
      name: "Liam Rodriguez",
      email: "liam.rodriguez@example.com",
      rollNumber: "2023002",
      branch: "CSE (AI AND ML)",
      year: "Second",
      semester: "3",
      gender: "Male",
    },
    {
      uid: "stu3",
      name: "Sophia Lee",
      email: "sophia.lee@example.com",
      rollNumber: "2023003",
      branch: "IT",
      year: "First",
      semester: "1",
      gender: "Female",
    },
    {
      uid: "stu4",
      name: "Noah Patel",
      email: "noah.patel@example.com",
      rollNumber: "2023004",
      branch: "AI AND DS",
      year: "Fourth",
      semester: "7",
      gender: "Male",
    },
    {
      uid: "stu5",
      name: "Emma Wilson",
      email: "emma.wilson@example.com",
      rollNumber: "2023005",
      branch: "CSE",
      year: "Third",
      semester: "5",
      gender: "Female",
    },
    {
      uid: "stu6",
      name: "Lucas Garcia",
      email: "lucas.garcia@example.com",
      rollNumber: "2023006",
      branch: "IT",
      year: "Second",
      semester: "3",
      gender: "Male",
    },
    {
      uid: "stu7",
      name: "Ava Miller",
      email: "ava.miller@example.com",
      rollNumber: "2023007",
      branch: "CSE",
      year: "First",
      semester: "1",
      gender: "Female",
    },
    {
      uid: "stu8",
      name: "Jackson Davis",
      email: "jackson.davis@example.com",
      rollNumber: "2023008",
      branch: "CSE (AI AND ML)",
      year: "Fourth",
      semester: "7",
      gender: "Male",
    },
    {
      uid: "stu9",
      name: "Mia Brown",
      email: "mia.brown@example.com",
      rollNumber: "2023009",
      branch: "AI AND DS",
      year: "Third",
      semester: "5",
      gender: "Female",
    },
    {
      uid: "stu10",
      name: "Oliver Jones",
      email: "oliver.jones@example.com",
      rollNumber: "2023010",
      branch: "CSE",
      year: "Second",
      semester: "3",
      gender: "Male",
    },
    {
      uid: "stu11",
      name: "Isabella Martinez",
      email: "isabella.martinez@example.com",
      rollNumber: "2023011",
      branch: "IT",
      year: "First",
      semester: "1",
      gender: "Female",
    },
    {
      uid: "stu12",
      name: "James Wilson",
      email: "james.wilson@example.com",
      rollNumber: "2023012",
      branch: "CSE",
      year: "Fourth",
      semester: "7",
      gender: "Male",
    },
    {
      uid: "stu13",
      name: "Charlotte Anderson",
      email: "charlotte.anderson@example.com",
      rollNumber: "2023013",
      branch: "AI AND DS",
      year: "Third",
      semester: "5",
      gender: "Female",
    },
    {
      uid: "stu14",
      name: "Ethan Thomas",
      email: "ethan.thomas@example.com",
      rollNumber: "2023014",
      branch: "CSE (AI AND ML)",
      year: "Second",
      semester: "3",
      gender: "Male",
    },
    {
      uid: "stu15",
      name: "Amelia Jackson",
      email: "amelia.jackson@example.com",
      rollNumber: "2023015",
      branch: "IT",
      year: "First",
      semester: "1",
      gender: "Female",
    },
    {
      uid: "stu16",
      name: "Benjamin White",
      email: "benjamin.white@example.com",
      rollNumber: "2023016",
      branch: "CSE",
      year: "Fourth",
      semester: "7",
      gender: "Male",
    },
    {
      uid: "stu17",
      name: "Harper Harris",
      email: "harper.harris@example.com",
      rollNumber: "2023017",
      branch: "AI AND DS",
      year: "Third",
      semester: "5",
      gender: "Female",
    },
    {
      uid: "stu18",
      name: "Alexander Martin",
      email: "alexander.martin@example.com",
      rollNumber: "2023018",
      branch: "CSE",
      year: "Second",
      semester: "3",
      gender: "Male",
    },
    {
      uid: "stu19",
      name: "Evelyn Taylor",
      email: "evelyn.taylor@example.com",
      rollNumber: "2023019",
      branch: "CSE (AI AND ML)",
      year: "First",
      semester: "1",
      gender: "Female",
    },
    {
      uid: "stu20",
      name: "Daniel Moore",
      email: "daniel.moore@example.com",
      rollNumber: "2023020",
      branch: "IT",
      year: "Fourth",
      semester: "7",
      gender: "Male",
    },
    {
      uid: "stu21",
      name: "Abigail King",
      email: "abigail.king@example.com",
      rollNumber: "2023021",
      branch: "CSE",
      year: "Third",
      semester: "5",
      gender: "Female",
    },
    {
      uid: "stu22",
      name: "Henry Scott",
      email: "henry.scott@example.com",
      rollNumber: "2023022",
      branch: "AI AND DS",
      year: "Second",
      semester: "3",
      gender: "Male",
    },
    {
      uid: "stu23",
      name: "Emily Green",
      email: "emily.green@example.com",
      rollNumber: "2023023",
      branch: "CSE (AI AND ML)",
      year: "First",
      semester: "1",
      gender: "Female",
    },
    {
      uid: "stu24",
      name: "Jacob Adams",
      email: "jacob.adams@example.com",
      rollNumber: "2023024",
      branch: "IT",
      year: "Fourth",
      semester: "7",
      gender: "Male",
    },
    {
      uid: "stu25",
      name: "Ella Baker",
      email: "ella.baker@example.com",
      rollNumber: "2023025",
      branch: "CSE",
      year: "Third",
      semester: "5",
      gender: "Female",
    },
    {
      uid: "stu26",
      name: "Michael Hall",
      email: "michael.hall@example.com",
      rollNumber: "2023026",
      branch: "CSE (AI AND ML)",
      year: "Second",
      semester: "3",
      gender: "Male",
    },
    {
      uid: "stu27",
      name: "Sofia Wright",
      email: "sofia.wright@example.com",
      rollNumber: "2023027",
      branch: "AI AND DS",
      year: "First",
      semester: "1",
      gender: "Female",
    },
    {
      uid: "stu28",
      name: "Joseph Hill",
      email: "joseph.hill@example.com",
      rollNumber: "2023028",
      branch: "IT",
      year: "Fourth",
      semester: "7",
      gender: "Male",
    },
    {
      uid: "stu29",
      name: "Madison Campbell",
      email: "madison.campbell@example.com",
      rollNumber: "2023029",
      branch: "CSE",
      year: "Third",
      semester: "5",
      gender: "Female",
    },
    {
      uid: "stu30",
      name: "David Mitchell",
      email: "david.mitchell@example.com",
      rollNumber: "2023030",
      branch: "CSE",
      year: "Second",
      semester: "3",
      gender: "Male",
    },
    {
      uid: "stu31",
      name: "Chloe Turner",
      email: "chloe.turner@example.com",
      rollNumber: "2023031",
      branch: "CSE (AI AND ML)",
      year: "First",
      semester: "1",
      gender: "Female",
    },
    {
      uid: "stu32",
      name: "Samuel Carter",
      email: "samuel.carter@example.com",
      rollNumber: "2023032",
      branch: "IT",
      year: "Fourth",
      semester: "7",
      gender: "Male",
    },
    {
      uid: "stu33",
      name: "Grace Phillips",
      email: "grace.phillips@example.com",
      rollNumber: "2023033",
      branch: "AI AND DS",
      year: "Third",
      semester: "5",
      gender: "Female",
    },
    {
      uid: "stu34",
      name: "Jack Evans",
      email: "jack.evans@example.com",
      rollNumber: "2023034",
      branch: "CSE",
      year: "Second",
      semester: "3",
      gender: "Male",
    },
    {
      uid: "stu35",
      name: "Avery Rivera",
      email: "avery.rivera@example.com",
      rollNumber: "2023035",
      branch: "CSE (AI AND ML)",
      year: "First",
      semester: "1",
      gender: "Male",
    },
    {
      uid: "stu36",
      name: "Zoe Torres",
      email: "zoe.torres@example.com",
      rollNumber: "2023036",
      branch: "IT",
      year: "Fourth",
      semester: "7",
      gender: "Female",
    },
    {
      uid: "stu37",
      name: "Sebastian Ramirez",
      email: "sebastian.ramirez@example.com",
      rollNumber: "2023037",
      branch: "CSE",
      year: "Third",
      semester: "5",
      gender: "Male",
    },
    {
      uid: "stu38",
      name: "Hannah Peterson",
      email: "hannah.peterson@example.com",
      rollNumber: "2023038",
      branch: "AI AND DS",
      year: "Second",
      semester: "3",
      gender: "Female",
    },
    {
      uid: "stu39",
      name: "Christian Powell",
      email: "christian.powell@example.com",
      rollNumber: "2023039",
      branch: "CSE",
      year: "First",
      semester: "1",
      gender: "Male",
    },
    {
      uid: "stu40",
      name: "Victoria Bell",
      email: "victoria.bell@example.com",
      rollNumber: "2023040",
      branch: "CSE (AI AND ML)",
      year: "Fourth",
      semester: "7",
      gender: "Female",
    },
    {
      uid: "stu41",
      name: "Gabriel Cook",
      email: "gabriel.cook@example.com",
      rollNumber: "2023041",
      branch: "IT",
      year: "Third",
      semester: "5",
      gender: "Male",
    },
    {
      uid: "stu42",
      name: "Lily Ward",
      email: "lily.ward@example.com",
      rollNumber: "2023042",
      branch: "CSE",
      year: "Second",
      semester: "3",
      gender: "Female",
    },
    {
      uid: "stu43",
      name: "Andrew Foster",
      email: "andrew.foster@example.com",
      rollNumber: "2023043",
      branch: "AI AND DS",
      year: "First",
      semester: "1",
      gender: "Male",
    },
    {
      uid: "stu44",
      name: "Addison Gray",
      email: "addison.gray@example.com",
      rollNumber: "2023044",
      branch: "CSE (AI AND ML)",
      year: "Fourth",
      semester: "7",
      gender: "Female",
    },
    {
      uid: "stu45",
      name: "Julian Brooks",
      email: "julian.brooks@example.com",
      rollNumber: "2023045",
      branch: "IT",
      year: "Third",
      semester: "5",
      gender: "Male",
    },
    {
      uid: "stu46",
      name: "Natalie Cooper",
      email: "natalie.cooper@example.com",
      rollNumber: "2023046",
      branch: "CSE",
      year: "Second",
      semester: "3",
      gender: "Female",
    },
    {
      uid: "stu47",
      name: "Ryan Hughes",
      email: "ryan.hughes@example.com",
      rollNumber: "2023047",
      branch: "CSE (AI AND ML)",
      year: "First",
      semester: "1",
      gender: "Male",
    },
    {
      uid: "stu48",
      name: "Samantha Bennett",
      email: "samantha.bennett@example.com",
      rollNumber: "2023048",
      branch: "AI AND DS",
      year: "Fourth",
      semester: "7",
      gender: "Female",
    },
    {
      uid: "stu49",
      name: "Jonathan Perry",
      email: "jonathan.perry@example.com",
      rollNumber: "2023049",
      branch: "IT",
      year: "Third",
      semester: "5",
      gender: "Male",
    },
    {
      uid: "stu50",
      name: "Bella Reed",
      email: "bella.reed@example.com",
      rollNumber: "2023050",
      branch: "CSE",
      year: "Second",
      semester: "3",
      gender: "Female",
    },
  ];
}
const page = async () => {
  const data = await getData()

  // const dummyStudents = [
  //   {
  //     uid: "stu1",
  //     name: "Alice Johnson",
  //     email: "alice.johnson@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023001",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE",
  //     year: "Third",
  //     semester: "5",
  //     dob: "2003-01-15",
  //     gender: "female",
  //     phone: "9876543210",
  //   },
  //   {
  //     uid: "stu2",
  //     name: "Bob Smith",
  //     email: "bob.smith@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023002",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE (AI AND ML)",
  //     year: "Second",
  //     semester: "3",
  //     dob: "2004-03-22",
  //     gender: "male",
  //     phone: "9123456780",
  //   },
  //   {
  //     uid: "stu3",
  //     name: "Charlie Brown",
  //     email: "charlie.brown@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023003",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "IT",
  //     year: "First",
  //     semester: "1",
  //     dob: "2005-06-10",
  //     gender: "male",
  //     phone: "9988776655",
  //   },
  //   {
  //     uid: "stu4",
  //     name: "Diana Prince",
  //     email: "diana.prince@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023004",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "AI AND DS",
  //     year: "Fourth",
  //     semester: "7",
  //     dob: "2002-12-05",
  //     gender: "female",
  //     phone: "9876501234",
  //   },
  //   {
  //     uid: "stu5",
  //     name: "Ethan Hunt",
  //     email: "ethan.hunt@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023005",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE",
  //     year: "Third",
  //     semester: "5",
  //     dob: "2003-09-18",
  //     gender: "male",
  //     phone: "9876549876",
  //   },
  //   {
  //     uid: "stu6",
  //     name: "Fiona Gallagher",
  //     email: "fiona.gallagher@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023006",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "ECE",
  //     year: "Fourth",
  //     semester: "7",
  //     dob: "2002-11-25",
  //     gender: "female",
  //     phone: "9123459876",
  //   },
  //   {
  //     uid: "stu7",
  //     name: "George Weasley",
  //     email: "george.weasley@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023007",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "Mech",
  //     year: "First",
  //     semester: "1",
  //     dob: "2005-02-14",
  //     gender: "male",
  //     phone: "9988771234",
  //   },
  //   {
  //     uid: "stu8",
  //     name: "Hannah Montana",
  //     email: "hannah.montana@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023008",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "Civil",
  //     year: "Second",
  //     semester: "3",
  //     dob: "2004-08-08",
  //     gender: "female",
  //     phone: "9876540987",
  //   },
  //   {
  //     uid: "stu9",
  //     name: "Ian Somerhalder",
  //     email: "ian.somerhalder@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023009",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE",
  //     year: "Third",
  //     semester: "5",
  //     dob: "2003-05-30",
  //     gender: "male",
  //     phone: "9123450987",
  //   },
  //   {
  //     uid: "stu10",
  //     name: "Jasmine Adams",
  //     email: "jasmine.adams@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023010",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE (AI AND ML)",
  //     year: "Fourth",
  //     semester: "7",
  //     dob: "2002-07-12",
  //     gender: "female",
  //     phone: "9988770987",
  //   },
  //   {
  //     uid: "stu11",
  //     name: "Kevin Peterson",
  //     email: "kevin.peterson@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023011",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "IT",
  //     year: "Third",
  //     semester: "5",
  //     dob: "2003-04-20",
  //     gender: "male",
  //     phone: "9876541234",
  //   },
  //   {
  //     uid: "stu12",
  //     name: "Lily Evans",
  //     email: "lily.evans@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023012",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "AI AND DS",
  //     year: "First",
  //     semester: "1",
  //     dob: "2005-08-01",
  //     gender: "female",
  //     phone: "9123451234",
  //   },
  //   {
  //     uid: "stu13",
  //     name: "Mike Ross",
  //     email: "mike.ross@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023013",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE",
  //     year: "Second",
  //     semester: "3",
  //     dob: "2004-06-25",
  //     gender: "male",
  //     phone: "9988771234",
  //   },
  //   {
  //     uid: "stu14",
  //     name: "Nancy Drew",
  //     email: "nancy.drew@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023014",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "ECE",
  //     year: "Fourth",
  //     semester: "7",
  //     dob: "2002-10-15",
  //     gender: "female",
  //     phone: "9876541234",
  //   },
  //   {
  //     uid: "stu15",
  //     name: "Oliver Queen",
  //     email: "oliver.queen@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023015",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "Mech",
  //     year: "Third",
  //     semester: "5",
  //     dob: "2003-02-18",
  //     gender: "male",
  //     phone: "9123451234",
  //   },
  //   {
  //     uid: "stu16",
  //     name: "Pam Beesly",
  //     email: "pam.beesly@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023016",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "Civil",
  //     year: "First",
  //     semester: "1",
  //     dob: "2005-09-03",
  //     gender: "female",
  //     phone: "9988771234",
  //   },
  //   {
  //     uid: "stu17",
  //     name: "Quentin Tarantino",
  //     email: "quentin.tarantino@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023017",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE",
  //     year: "Fourth",
  //     semester: "7",
  //     dob: "2002-05-27",
  //     gender: "male",
  //     phone: "9876541234",
  //   },
  //   {
  //     uid: "stu18",
  //     name: "Rachel Green",
  //     email: "rachel.green@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023018",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE (AI AND ML)",
  //     year: "Second",
  //     semester: "3",
  //     dob: "2004-01-09",
  //     gender: "female",
  //     phone: "9123451234",
  //   },
  //   {
  //     uid: "stu19",
  //     name: "Steve Rogers",
  //     email: "steve.rogers@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023019",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "IT",
  //     year: "Third",
  //     semester: "5",
  //     dob: "2003-07-21",
  //     gender: "male",
  //     phone: "9988771234",
  //   },
  //   {
  //     uid: "stu20",
  //     name: "Tanya Sharma",
  //     email: "tanya.sharma@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023020",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "AI AND DS",
  //     year: "Fourth",
  //     semester: "7",
  //     dob: "2002-03-04",
  //     gender: "female",
  //     phone: "9876541234",
  //   },
  //   {
  //     uid: "stu21",
  //     name: "Umesh Kumar",
  //     email: "umesh.kumar@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023021",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE",
  //     year: "First",
  //     semester: "1",
  //     dob: "2005-11-29",
  //     gender: "male",
  //     phone: "9123451234",
  //   },
  //   {
  //     uid: "stu22",
  //     name: "Victoria Johnson",
  //     email: "victoria.johnson@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023022",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "ECE",
  //     year: "Second",
  //     semester: "3",
  //     dob: "2004-02-12",
  //     gender: "female",
  //     phone: "9988771234",
  //   },
  //   {
  //     uid: "stu23",
  //     name: "William Turner",
  //     email: "william.turner@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023023",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "Mech",
  //     year: "Third",
  //     semester: "5",
  //     dob: "2003-08-19",
  //     gender: "male",
  //     phone: "9876541234",
  //   },
  //   {
  //     uid: "stu24",
  //     name: "Xena Warrior",
  //     email: "xena.warrior@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023024",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "Civil",
  //     year: "Fourth",
  //     semester: "7",
  //     dob: "2002-09-01",
  //     gender: "female",
  //     phone: "9123451234",
  //   },
  //   {
  //     uid: "stu25",
  //     name: "Yash Chopra",
  //     email: "yash.chopra@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023025",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE",
  //     year: "First",
  //     semester: "1",
  //     dob: "2005-04-14",
  //     gender: "male",
  //     phone: "9988771234",
  //   },
  //   {
  //     uid: "stu26",
  //     name: "Zoe Hart",
  //     email: "zoe.hart@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023026",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE (AI AND ML)",
  //     year: "Third",
  //     semester: "5",
  //     dob: "2003-10-05",
  //     gender: "female",
  //     phone: "9876541234",
  //   },
  //   {
  //     uid: "stu27",
  //     name: "Aarav Patel",
  //     email: "aarav.patel@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023027",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "IT",
  //     year: "Second",
  //     semester: "3",
  //     dob: "2004-12-30",
  //     gender: "male",
  //     phone: "9123451234",
  //   },
  //   {
  //     uid: "stu28",
  //     name: "Bhavya Singh",
  //     email: "bhavya.singh@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023028",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "AI AND DS",
  //     year: "Fourth",
  //     semester: "7",
  //     dob: "2002-06-28",
  //     gender: "female",
  //     phone: "9988771234",
  //   },
  //   {
  //     uid: "stu29",
  //     name: "Chirag Sharma",
  //     email: "chirag.sharma@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023029",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE",
  //     year: "First",
  //     semester: "1",
  //     dob: "2005-01-18",
  //     gender: "male",
  //     phone: "9876541234",
  //   },
  //   {
  //     uid: "stu30",
  //     name: "Deepika Kumari",
  //     email: "deepika.kumari@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023030",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "ECE",
  //     year: "Third",
  //     semester: "5",
  //     dob: "2003-03-16",
  //     gender: "female",
  //     phone: "9123451234",
  //   },
  //   {
  //     uid: "stu31",
  //     name: "Eshaan Das",
  //     email: "eshaan.das@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023031",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "Mech",
  //     year: "Second",
  //     semester: "3",
  //     dob: "2004-07-07",
  //     gender: "male",
  //     phone: "9988771234",
  //   },
  //   {
  //     uid: "stu32",
  //     name: "Farah Khan",
  //     email: "farah.khan@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023032",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "Civil",
  //     year: "Third",
  //     semester: "5",
  //     dob: "2003-05-12",
  //     gender: "female",
  //     phone: "9876541234",
  //   },
  //   {
  //     uid: "stu33",
  //     name: "Gaurav Singh",
  //     email: "gaurav.singh@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023033",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE",
  //     year: "Fourth",
  //     semester: "7",
  //     dob: "2002-04-24",
  //     gender: "male",
  //     phone: "9123451234",
  //   },
  //   {
  //     uid: "stu34",
  //     name: "Hina Malik",
  //     email: "hina.malik@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023034",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE (AI AND ML)",
  //     year: "First",
  //     semester: "1",
  //     dob: "2005-03-10",
  //     gender: "female",
  //     phone: "9988771234",
  //   },
  //   {
  //     uid: "stu35",
  //     name: "Ishan Jain",
  //     email: "ishan.jain@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023035",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "IT",
  //     year: "Second",
  //     semester: "3",
  //     dob: "2004-09-02",
  //     gender: "male",
  //     phone: "9876541234",
  //   },
  //   {
  //     uid: "stu36",
  //     name: "Jhanvi Mehta",
  //     email: "jhanvi.mehta@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023036",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "AI AND DS",
  //     year: "Third",
  //     semester: "5",
  //     dob: "2003-01-28",
  //     gender: "female",
  //     phone: "9123451234",
  //   },
  //   {
  //     uid: "stu37",
  //     name: "Kabir Soni",
  //     email: "kabir.soni@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023037",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE",
  //     year: "First",
  //     semester: "1",
  //     dob: "2005-07-09",
  //     gender: "male",
  //     phone: "9988771234",
  //   },
  //   {
  //     uid: "stu38",
  //     name: "Lakshmi Iyer",
  //     email: "lakshmi.iyer@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023038",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "ECE",
  //     year: "Fourth",
  //     semester: "7",
  //     dob: "2002-08-11",
  //     gender: "female",
  //     phone: "9876541234",
  //   },
  //   {
  //     uid: "stu39",
  //     name: "Manoj Kumar",
  //     email: "manoj.kumar@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023039",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "Mech",
  //     year: "Second",
  //     semester: "3",
  //     dob: "2004-10-23",
  //     gender: "male",
  //     phone: "9123451234",
  //   },
  //   {
  //     uid: "stu40",
  //     name: "Neha Gupta",
  //     email: "neha.gupta@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023040",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "Civil",
  //     year: "Third",
  //     semester: "5",
  //     dob: "2003-02-05",
  //     gender: "female",
  //     phone: "9988771234",
  //   },
  //   {
  //     uid: "stu41",
  //     name: "Omkar Jadhav",
  //     email: "omkar.jadhav@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023041",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE",
  //     year: "Fourth",
  //     semester: "7",
  //     dob: "2002-06-19",
  //     gender: "male",
  //     phone: "9876541234",
  //   },
  //   {
  //     uid: "stu42",
  //     name: "Pooja Singh",
  //     email: "pooja.singh@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023042",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE (AI AND ML)",
  //     year: "First",
  //     semester: "1",
  //     dob: "2005-09-17",
  //     gender: "female",
  //     phone: "9123451234",
  //   },
  //   {
  //     uid: "stu43",
  //     name: "Rahul Tiwari",
  //     email: "rahul.tiwari@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023043",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "IT",
  //     year: "Second",
  //     semester: "3",
  //     dob: "2004-03-29",
  //     gender: "male",
  //     phone: "9988771234",
  //   },
  //   {
  //     uid: "stu44",
  //     name: "Shruti Agarwal",
  //     email: "shruti.agarwal@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023044",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "AI AND DS",
  //     year: "Third",
  //     semester: "5",
  //     dob: "2003-12-08",
  //     gender: "female",
  //     phone: "9876541234",
  //   },
  //   {
  //     uid: "stu45",
  //     name: "Tarun Reddy",
  //     email: "tarun.reddy@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023045",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE",
  //     year: "First",
  //     semester: "1",
  //     dob: "2005-05-22",
  //     gender: "male",
  //     phone: "9123451234",
  //   },
  //   {
  //     uid: "stu46",
  //     name: "Uma Shankar",
  //     email: "uma.shankar@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023046",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "ECE",
  //     year: "Third",
  //     semester: "5",
  //     dob: "2003-09-09",
  //     gender: "female",
  //     phone: "9988771234",
  //   },
  //   {
  //     uid: "stu47",
  //     name: "Vivek Kumar",
  //     email: "vivek.kumar@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023047",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "Mech",
  //     year: "Fourth",
  //     semester: "7",
  //     dob: "2002-01-01",
  //     gender: "male",
  //     phone: "9876541234",
  //   },
  //   {
  //     uid: "stu48",
  //     name: "Winnie Singh",
  //     email: "winnie.singh@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023048",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "Civil",
  //     year: "Second",
  //     semester: "3",
  //     dob: "2004-11-13",
  //     gender: "female",
  //     phone: "9123451234",
  //   },
  //   {
  //     uid: "stu49",
  //     name: "Yogesh Sharma",
  //     email: "yogesh.sharma@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023049",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "CSE",
  //     year: "Third",
  //     semester: "5",
  //     dob: "2003-04-04",
  //     gender: "male",
  //     phone: "9988771234",
  //   },
  //   {
  //     uid: "stu50",
  //     name: "Zoya Afsar",
  //     email: "zoya.afsar@example.com",
  //     college: "Hi-Tech Institute of Technology, Aurangabad",
  //     rollNumber: "2023050",
  //     course: "BTech (Bachelor of Technology)",
  //     branch: "AI AND DS",
  //     year: "Fourth",
  //     semester: "7",
  //     dob: "2002-10-25",
  //     gender: "female",
  //     phone: "9876541234",
  //   },
  // ];


  // Fetch students from Firestore

  return (
    <div className="container mx-auto py-10">
      <DataTable columns={columns} data={data} />
    </div>
  )
}

export default page
